DscResources/MSFT_UserResource/MSFT_UserResource.psm1, DscResources/MSFT_UserResource/en-US/MSFT_UserResource.strings.psd1, README.md, Tests/Integration/MSFT_UserResource.Integration.Tests.ps1, Tests/Integration/MSFT_UserResource.config.ps1, Tests/Unit/MSFT_UserResource.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/24)
=> Updating User

Tests/Integration/MSFT_RegistryResource.EndToEnd.Tests.ps1, Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, Tests/Integration/MSFT_WindowsPackageCab.config.ps1, Tests/Integration/WindowsFeatureSet.Integration.Tests.ps1, Tests/TestHelpers/WMF5Dot1Installation.psm1, appveyor.yml
Adding a module to install the recently-released WMF 5.1 on AppVeyor so that the integration tests will now run automatically.
I had to skip two tests in WindowsFeature which tested installing and uninstalling a feature with subfeatures. These tests were causing a pending reboot to occur which would later cause the second resource to never run in both the WindowsFeatureSet and WindowsOptionalFeatureSet tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/28)
=> Install WMF 5.1 on AppVeyor so integration tests run

DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1, README.md, Tests/Integration/MSFT_GroupResource.Integration.Tests.ps1, Tests/Integration/MSFT_GroupResource_NoMembers.config.ps1, appveyor.yml
This should fix #26, but I do not want to close that issue until the author has confirmed that this fix works for them as well.
There have been multiple issues opened about the error that the 'server names cannot contain a space character'. That was occurring because the resource was searching for a *domain* principal context for group members in the 'NT Authority' scope. The fix for this is to search for those users in the *machine* principal context instead. 
This PR also includes a fix in which the resource will no longer attempt to retrieve the group members when no members are specified.
I have added new integration tests for both cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Add 'NT Authority' to local machine scopes

DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1, README.md, Tests/Integration/MSFT_GroupResource_NoMembers.config.ps1
This is a local scope on database or SqlServer machines.
I can't add tests for it since I don't have either of those machines in our test environment, but it should fix any issues coming up with resolving NT Service members in a group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/31)
=> Group: Add NT Service to list of local scopes

DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1, README.md
Resolution for Issue [38](https://github.com/PowerShell/PSDscResources/issues/38)
Adds support for domain based group members on nano server.
This is a very important feature to be able to control the local administrators on a nano server without having GPOs/Restricted Groups.
If i missed anything i would gladly change :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/39)
=> Added Support for domain based group members on Nano Server

DscResources/CommonResourceHelper.psm1, README.md, Tests/Unit/CommonResourceHelper.Tests.ps1
I have updated Test-IsNanoServer to correctly test for a Nano server rather than for the core version of PowerShell with the code provided in #11.
I have also added unit tests for both Test-IsNanoServer and the new common function Test-CommandExists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/42)
=> Fix Test-IsNanoServer to actually test for a NanoServer (Fixes #11)

DscResources/MSFT_RegistryResource/MSFT_RegistryResource.psm1, README.md, Tests/Integration/MSFT_RegistryResource.EndToEnd.Tests.ps1
Fixed a bug in which Registry would always throw an error when Get-DscConfiguration was called if the registry key already existed.
Also added tests to make sure Get-DscConfiguration works for Registry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/44)
=> Registry: Fix Get-DscConfiguration

DscResources/MSFT_MsiPackage/MSFT_MsiPackage.psm1, Tests/Unit/MSFT_MsiPackage.Tests.ps1
Hello,
I found out that a unit-test in MSFT_MsiPackage.Tests.ps1 fails on a computer with non-English regional settings. The failing unit-test is:
- Describing Get-ProductEntryInfo
- Context All properties are retrieved successfully
- Should return the expected installed date
The problem is that it asserts date formatted in en-US culture.
So I changed the test that it asserts date formatted in current culture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/54)
=> Verify InstalledOn date in correct culture in MSFT_MsiPackage unit test

.gitignore, DscResources/MSFT_Archive/MSFT_Archive.psm1, README.md, Tests/Unit/MSFT_Archive.Tests.ps1, appveyor.yml
Directory archive entries can end in either a backslash or a forward slash. The resource was only handling the backslash and crashing on the forward slash case, so I added handling for the forward slash.
I have added new unit tests for this as well, but I'm not sure how to dynamically create an archive with directory archive entries that end in forward slashes on a Windows machine, so integration testing was not added for this case.
I have also added the import of Microsoft.PowerShell.Utility to the resource as it could not find the function Get-FileHash on a Windows 10 machine with the Creators  Update.
This should fix #67.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdsc …
=> Archive: Add handling for directory archive entries ending with a forward slash (Fixes #67)

DscResources/CommonResourceHelper.psm1, README.md, Tests/Unit/CommonResourceHelper.Tests.ps1
Test-IsNanoServer will now return false if Get-ComputerInfo fails rather than failing itself.
This should fix #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/75)
=> Update Test-IsNanoServer to return false if Get-ComputerInfo fails

DscResources/MSFT_Archive/MSFT_Archive.psm1, README.md, Tests/Integration/MSFT_Archive.EndToEnd.Tests.ps1, Tests/Integration/MSFT_Archive.Integration.Tests.ps1, Tests/Unit/MSFT_Archive.Tests.ps1
I have removed the Get-Date function from the resource entirely.
That function was what was causing a problem with dates from cultures that were not en-US since it always defaults to en-US dates rather than the appropriately cultured date.
This should fix #61 though I can't personally reproduce the culture problem to confirm that the issue is fixed so I will leave the issue open until it is confirmed fixed.
I also fixed an issue with the Archive resource on Windows 10 in which it hadn't properly loaded the Get-FileHash function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/74)
=> Fix Archive culture problems with timestamp

DscResources/MSFT_RegistryResource/MSFT_RegistryResource.psm1, README.md, Tests/Integration/MSFT_RegistryResource.EndToEnd.Tests.ps1, Tests/Unit/MSFT_RegistryResource.Tests.ps1
I fixed a bug when using the full registry drive name (e.g. HKEY\_LOCAL\_MACHINE) and using a key name that includes a drive with forward slashes (e.g. C:/). (Fixes #68)
I also added an integration test for this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/78)
=> Registry: Fixed bug when registry name contains drive

README.md, Tests/Unit/CommonResourceHelper.Tests.ps1, Tests/Unit/ResourceSetHelper.Tests.ps1
This PR:
* Update `CommonResourceHelper` unit tests to meet Pester 4.0.0
standards ([issue #129](https://github.com/PowerShell/PSDscResources/issues/129)).
* Update `ResourceHelper` unit tests to meet Pester 4.0.0
standards ([issue #129](https://github.com/PowerShell/PSDscResources/issues/129)).
- Does not fix any issues but contributes to #129
@johlju would you mind reviewing when you get a moment. Should be straight forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xpsdesiredstateconfiguration/475)
=> Update CommonResourceHelper and ResourceHelper tests to Pester 4 standards

DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1, README.md, Tests/Integration/GroupSet.Integration.Tests.ps1, Tests/Integration/GroupSet.config.ps1, Tests/Integration/MSFT_GroupResource.Integration.Tests.ps1, Tests/Integration/MSFT_GroupResource_Members.config.ps1, Tests/Integration/MSFT_GroupResource_MembersToIncludeExclude.config.ps1, Tests/Integration/MSFT_GroupResource_NoMembers.config.ps1, Tests/Unit/MSFT_GroupResource.Tests.ps1
This PR refactors Group and GroupSet tests to meet Pester 4 standards. Also made some tweaks to the tests to use Pester It block `-TestCases` for some tests.
I also tweaked the README.MD style to remove : after resource titles as this is the standard (I had been doing it wrong myself :grin:).
- Contributes to #129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/135)
=> Update Group and GroupSet tests to meet Pester 4 standards

PSDscResources.psd1, README.md
Fix typo in company name
- Fixes #100 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/138)
=> PSDscResources: Fix for Issue #100 - typo in company name

README.md, Tests/Integration/MSFT_MsiPackage.EndToEnd.Tests.ps1, Tests/Integration/MSFT_MsiPackage.Integration.Tests.ps1, Tests/TestHelpers/CommonTestHelper.psm1
Fixes issue where MsiPackage Integration tests fail if strong crypto is not enabled for .NET 4.
- Fixes #142 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/143)
=> Fix msi package tests

README.md, Tests/Integration/MSFT_MsiPackage.EndToEnd.Tests.ps1, Tests/Integration/MSFT_MsiPackage.Integration.Tests.ps1, Tests/TestHelpers/CommonTestHelper.psm1
Reverts PowerShell/PSDscResources#143, as it did not ultimately solve the issue described in #142. I do have a real (I hope) fix ready to go, as well as some logging updates, but would like to get this unnecessary change reverted first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/156)
=> Revert "Fix msi package tests"

DscResources/MSFT_MsiPackage/MSFT_MsiPackage.psm1, README.md, Tests/Integration/MSFT_MsiPackage.EndToEnd.Tests.ps1, Tests/Integration/MSFT_MsiPackage.Integration.Tests.ps1, Tests/TestHelpers/CommonTestHelper.psm1, Tests/TestHelpers/MSFT_MsiPackageResource.TestHelper.psm1, Tests/Unit/MSFT_MsiPackage.Tests.ps1
* Fixes issue where MsiPackage Integration tests fail if the test HttpListener
fails to start. Moves the test HttpListener objects to dynamically assigned,
higher numbered ports to avoid conflicts with other services, and also checks
to ensure that the ports are available before using them. Adds checks to
ensure that no outstanding HTTP server jobs are running before attempting to
setup a new one. Also adds additional instrumentation to make it easier to
troubleshoot issues with the test HttpListener objects in the future.
- Fixes #142 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> MSFT_MsiPackage: Fix HttpListener Issues with MsiPackage Integration Tests

DscResources/CommonResourceHelper.psm1, README.md, Tests/Unit/CommonResourceHelper.Tests.ps1
Currently, the Test-IsNanoServer function calls the Get-ComputerInfo cmdlet to check with the computer is running Nano server or not. Get-ComputerInfo can take 40+ seconds to run each time. This function is called for each user and group resource within a Dsc configuration and therefore can make the Dsc application very slow.
This PR replaces Get-ComputerInfo with checking the registry value at HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Server\ServerLevels\NanoServer, as documented here: https://msdn.microsoft.com/en-us/library/windows/desktop/hh846315(v=vs.85).aspx
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Improve speed of Test-IsNanoServer function

README.md
This PR fixes the following markdownlint validation failures IN README.md that are reported in the current AppVeyor tests:
```
C:\projects\psdscresources\README.md: 683: MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
C:\projects\psdscresources\README.md: 20: MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```powershell"]
C:\projects\psdscresources\README.md: 25: MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```powershell"]
C:\projects\psdscresources\README.md: 1: MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "master: [![Build status](https..."]
```
To fix `MD041`, the build/code coverage information has been moved into a …
=> Fix README Markdownlint Validation Failures

CHANGELOG.md, DscResources/CommonResourceHelper.psm1, DscResources/GroupSet/GroupSet.schema.psm1, DscResources/MSFT_Archive/MSFT_Archive.psm1, DscResources/MSFT_EnvironmentResource/MSFT_EnvironmentResource.psm1, DscResources/MSFT_GroupResource/MSFT_GroupResource.psm1, DscResources/MSFT_MsiPackage/MSFT_MsiPackage.psm1, DscResources/MSFT_RegistryResource/MSFT_RegistryResource.psm1, DscResources/MSFT_ScriptResource/MSFT_ScriptResource.psm1, DscResources/MSFT_ServiceResource/MSFT_ServiceResource.psm1, DscResources/MSFT_UserResource/MSFT_UserResource.psm1, DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, DscResources/MSFT_WindowsOptionalFeature/MSFT_WindowsOptionalFeature.psm1, DscResources/MSFT_WindowsPackageCab/MSFT_WindowsPackageCab.psm1, DscResources/MSFT_WindowsProcess/MSFT_WindowsProcess.psm1, DscResources/ProcessSet/ProcessSet.schema.psm1, DscResources/ResourceSetHelper.psm1, DscResources/ServiceSet/ServiceSet.schema.psm1, DscResources/WindowsFeatureSet/WindowsFeatureSet.schema.psm1, DscResources/WindowsOptionalFeatureSet/WindowsOptionalFeatureSet.schema.psm1, Tests/Unit/MSFT_GroupResource.Tests.ps1, Tests/Unit/MSFT_ServiceResource.Tests.ps1, Tests/Unit/MSFT_WindowsFeature.Tests.ps1
Ports most of the style upgrades from xPSDesiredStateConfiguration that have been made in files in the DscResources folder. Among other things, this will help to ensure that the two modules are as in sync as possible, which will in turn help with porting changes and features between modules.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/psdscresources/162)
=> Port Style Upgrades in DscResources Folder from xPSDesiredStateConfiguration
